version: 2

jobs:
  test:
    machine: true
    steps:
      - checkout
      - run: git clone https://github.com/ConnextProject/indra.git && cd indra && npm start && cd -
      - run: npm run test

workflows:
  version: 2
  test:
    jobs:
      - test
