version: 2

jobs:
  test:
    machine: true
    steps:
      - checkout
      - run: make test

  push-images:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: make push

  push-live-images:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: make push-live

  deploy-staging:
    machine: true
    steps:
      - run: ssh ubuntu@$STAGING_URL "bash -c 'git clone https://github.com/ConnextProject/card.git || true'"
      - run: ssh ubuntu@$STAGING_URL "bash -c 'cd card && git fetch && git reset --hard origin/"$CIRCLE_BRANCH "'"
      - run: ssh ubuntu@$STAGING_URL "bash -c 'cd card && DOMAINNAME="$STAGING_URL "bash ops/restart.sh prod'"

  deploy-live:
    machine: true
    steps:
      - run: ssh ubuntu@$PRODUCTION_URL "bash -c 'git clone https://github.com/ConnextProject/card.git || true'"
      - run: ssh ubuntu@$PRODUCTION_URL "bash -c 'cd card && git fetch && git reset --hard origin/master'"
      - run: ssh ubuntu@$PRODUCTION_URL "bash -c 'cd card && MODE=live DOMAINNAME="$PRODUCTION_URL "bash ops/restart.sh prod'"

workflows:
  version: 2
  test:
    jobs:
      - test
